Class {
	#name : 'FASTXMLTokenizedType',
	#superclass : 'FASTXMLEntity',
	#traits : 'FASTXMLTAttType',
	#classTraits : 'FASTXMLTAttType classTrait',
	#category : 'FAST-XML-Model-Entities',
	#package : 'FAST-XML-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTXMLTokenizedType class >> annotation [

	<ignoreForCoverage>
	<FMClass: #TokenizedType super: #FASTXMLEntity>
	<package: #'FAST-XML-Model'>
	<generated>
]
