Class {
	#name : 'FASTXMLComment',
	#superclass : 'FASTXMLEntity',
	#traits : 'FASTXMLTMarkupdecl',
	#classTraits : 'FASTXMLTMarkupdecl classTrait',
	#category : 'FAST-XML-Model-Entities',
	#package : 'FAST-XML-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTXMLComment class >> annotation [

	<ignoreForCoverage>
	<FMClass: #Comment super: #FASTXMLEntity>
	<package: #'FAST-XML-Model'>
	<generated>
]
