"
## Relations
======================

### Parents
| Relation | Origin | Opposite | Type | Comment |
|---|
| `attValueContentOwner` | `FASTXMLTReference` | `content` | `FASTXMLAttValue` | |
| `pseudoAttValueContentOwner` | `FASTXMLTReference` | `content` | `FASTXMLPseudoAttValue` | |



"
Class {
	#name : 'FASTXMLCharRef',
	#superclass : 'FASTXMLEntity',
	#traits : 'FASTXMLTReference',
	#classTraits : 'FASTXMLTReference classTrait',
	#category : 'FAST-XML-Model-Entities',
	#package : 'FAST-XML-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTXMLCharRef class >> annotation [

	<ignoreForCoverage>
	<FMClass: #CharRef super: #FASTXMLEntity>
	<package: #'FAST-XML-Model'>
	<generated>
]
